parsing_logs_worker:
  cron: "/3 * * * *"
  class: "ParsingLogsWorker"
  queue: default
scheduler_parse_channel_workers:
  cron: "0 * * * *"
  class: "SchedulerParseChannelWorker"
  queue: critical
update_channel_info_workers:
  cron: "/5 * * * *"
  class: "UpdateChannelsWorker"
  queue: critical
# upsert_post_views_workers:
#   cron: "*/1 * * * *"
#   class: "UpsertPostsWorker"
#   queue: critical
create_post_views_workers:
  cron: "*/1 * * * *"
  class: "CreatePostsWorker"
  queue: critical
update_post_views_workers:
  cron: "*/1 * * * *"
  class: "UpdatePostsWorker"
  queue: critical



